import { StyleSheet, Platform } from 'react-native';
import { Dimensions } from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    backgroundColor: '#232323',
    flex: 1,
    flexDirection: "column",
    width: '100%',
    height: '100%',
    padding: 10,
    position: 'relative',
  },
  termsTitle: {
    fontFamily: 'Heebo-Bold',
    fontSize: 30,
    color: 'white',
    textTransform: 'uppercase',
    textAlign: 'center',
    marginBottom: 20,
  },
  termsText: {
    fontFamily: 'Heebo-Light',
    fontSize: 20,
    color: 'white',
    textAlign: 'center',
  },
  firstTimeSlide: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideTitle: {
    fontFamily: 'Heebo-Bold',
    fontSize: 30,
    color: 'white',
    textTransform: 'uppercase',
    textAlign: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  slideDescription: {
    fontFamily: 'Heebo-Light',
    fontSize: 20,
    color: 'white',
    textAlign: 'center'
  },
  treciPesteButonText: {
    fontFamily: 'Heebo-Medium',
    color: '#E3051B',
    fontSize: 18,
    textTransform: 'uppercase'
  },
  swiperContainer: {
    height: '75%',
    marginBottom: 20,
  },
  headerContainerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 87,
    backgroundColor: 'black',
    padding: 10,
  },
  cartButton: {
    position: 'relative',
    marginRight: 5,
  },
  cartBula: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    width: 23,
    height: 23,
    borderRadius: 50,
    position: 'absolute',
    top: -15,
    right: -8,
    overflow: 'hidden'
  },
  bulaNumar: {
    fontFamily: 'Heebo-Bold',
    fontSize: 13,
    color: '#E3051B',
  },
  footerContainer: {
    backgroundColor: 'black',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    width: '100%',
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
    position: 'absolute',
    bottom: 0,
  },
  footerButton: {
    width: '33%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    textAlign: 'center',
    fontFamily: 'Heebo-Light',
    fontSize: 12,
    color: 'white',
    marginTop: 5,
  },
  contentScrollView: {
    width: '100%',
    backgroundColor: '#232323',
    flex: 1,
  },
  ofertaContainer: {
    backgroundColor: '#999999',
    width: '92%',
    alignSelf: 'center',
    height: 'auto',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 20,
    marginTop: 10,
    borderRadius: 20,
    position: 'relative',
  },
  ofertaTextContainer: {
    marginLeft: 10,
    flexDirection: 'column',
  },
  ofertaTitleIndex: {
    fontFamily: 'Heebo-Medium',
    fontSize: 14,
    textTransform: 'uppercase',
    color: 'black',
  },
  ofertaSubtitle: {
    fontFamily: 'Heebo-Light',
    fontSize: 14,
    color: 'black',
  },
  closeOferte: {
    width: 16,
    height: 16,
    zIndex: 20,
    top: -10,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center'
  },
  produsContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'black',
    flex: 1,
  },
  produsImagine: {
    width: 74,
    height: 74,
    flexShrink: 0,
  },
  imageProdus: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  produsTitle: {
    fontFamily: 'Heebo-Bold',
    fontSize: 16,
    color: 'white',
    marginBottom: 10,
  },
  produsDescriere: {
    fontFamily: 'Heebo-Light',
    fontSize: 11,
    color: 'white',
    marginBottom: 10,
    width: '95%'
  },
  produsTag: {
    backgroundColor: '#4D4D4D',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 5,
    paddingRight: 5,
    marginRight: 10,
  },
  tagNou: {
    width: 'auto', textAlign: 'center', borderRadius: 7, fontSize: 10, fontFamily: 'Heebo-Regular', color: '#FFD101', textTransform: 'uppercase', paddingVertical: 3, paddingHorizontal: 10, backgroundColor: '#000', overflow:"hidden"
  },
  tagPiccante: {
    width: 80, textAlign: 'center', borderRadius: 7, fontSize: 10, fontFamily: 'Heebo-Regular', color: '#E3051B', textTransform: 'uppercase', paddingVertical: 3, paddingHorizontal: 10, backgroundColor: '#000', overflow:"hidden"
  },
  tagText: {
    fontFamily: 'Heebo-Medium',
    fontSize: 10,
  },
  produsDimensiune: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    height: 38,
    marginBottom: 10,
    width: '100%',
    borderRadius: 5,
    overflow: 'hidden',
  },
  produsDimensiuneCustom: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 38,
    marginBottom: 10,
    width: '100%',
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: '#999999',
  },
  produsDimensiuneStanga: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFD101',
    borderRightColor: '#E3051B',
    borderRightWidth: 2,
    width: '48%',
  },
  produsDimensiuneMarime: {
    fontFamily: 'Heebo-Bold',
    fontSize: 14,
    color: 'black',
    textAlign: 'center',
  },
  produsDimensiuneCm: {
    fontFamily: 'Heebo-Regular',
    fontSize: 11,
    color: 'black',
    textAlign: 'center',
    
  },
  produsTextContainer: {
    width: '43%',
    marginLeft: 7,
    marginRight: 7,
  },
  produsDimensiuni: {
    flexDirection: 'column',
    width: '30%',
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  produsPret: {
    fontFamily: 'Heebo-Bold',
    color: 'white',
    fontSize: 14,
  },
  produsLei: {
    fontFamily: 'Heebo-Regular',
    color: 'white',
    fontSize: 11,
    marginLeft: 3,
  },
  produsDimensiuneDreapta: {
    backgroundColor: '#999999',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    height: '100%',
    width: '52%',
  },
  produsDimensiuneCustomText: {
    fontFamily: 'Heebo-Bold',
    color: 'white',
    fontSize: 11,
    textTransform: 'uppercase',
  },
  menuElement: {
    backgroundColor: '#232323',
    width: '49%',
    height: 110,
    marginBottom: 10,
    borderRadius: 10,
    overflow: 'hidden',
  },
  menuElementButton: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuText: {
    fontFamily: 'Mongoose-Regular',
    fontSize: 31,
    color: '#FFD101',
    textTransform: 'uppercase',
    marginTop: 10,
  },
  oferteTitle: {
    fontFamily: 'Heebo-Bold',
    fontSize: 25,
    color: 'white',
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  oferta: {
    marginBottom: 40,
    backgroundColor: 'black',
    width: '100%'
  },
  fullWidth: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  ofertImagine: {
    width: '100%',
    height: 229,
  },
  ofertaTextContianer: {
    marginTop: 20,
  },
  ofertaTitle: {
    fontFamily: 'Heebo-Bold',
    fontSize: 30,
    color: 'white',
    textAlign: 'center',
    marginBottom: 10,
  },
  ofertaDescriere: {
    fontFamily: 'Heebo-Light',
    fontSize: 16,
    color: 'white',
    textAlign: 'center',
    marginBottom: 20,
    width: '60%',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  ofertaPretContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    flexShrink:0,
  },
  ofertaPret: {
    fontFamily: 'Heebo-Bold',
    fontSize: 33,
    color: '#FFD100',
  },
  ofertaLei: {
    fontFamily: 'Heebo-Regular',
    fontSize: 18,
    color: '#FFD100',
    marginLeft: 5,
  },
  warningMessage: {
    flexDirection: "row",
    backgroundColor: "#E3051B",
    alignItems: "center",
    borderRadius: 5,
  },
  warningOferta: {
    color: "#FFD100",
    fontSize: 30,
    fontFamily: 'Heebo-Bold',
    textAlign: 'center'
  },
  cosItemTitle: {
    fontSize: 18,
    fontFamily: 'Heebo-Regular',
    color: "white",
  },
  cosItemDetails: {
    fontSize: 14,
    fontFamily: 'Heebo-Light',
    color: "#fff",
    opacity: 0.5,
    flexWrap: 'wrap',
    width: '100%',
  },
  adaugaCos: {
    backgroundColor: '#999999',
    height: 54,
    width: '80%',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 10,
    marginBottom: 20,
    marginTop: 20,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  mainButton: {
    height: 54,
    borderRadius: 10,
    marginBottom: 20,
    marginTop: 20,
    backgroundColor: '#999999',
    overflow: 'hidden',
  },
  adaugaCosText: {
    color: 'white',
    textTransform: 'uppercase',
    fontFamily: 'Heebo-Medium',
    fontSize: 15,
  },
  adaugaCosLeft: {
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  adaugaCosRight: {
    width: '30%',
  },
  detaliuPizzaPoza: {
    width: '100%',
    height: 229,
    marginTop: 10,
    marginBottom: 10,
  },
  detaliuProdusTitle: {
    fontFamily: 'Heebo-Bold',
    fontSize: 30,
    color: 'white',
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  ingredienteText: {
    fontFamily: 'Heebo-Regular',
    fontSize: 16,
    color: 'white',
    width: '80%',
    flexWrap: "wrap",
  },
  ingredientText: {
    fontFamily: 'Heebo-Regular',
    fontSize: 12,
    color: '#B3B3B3',
    marginLeft: 8,
  },
  igredient: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 13,
    paddingRight: 13,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },

  descreireIngrediente: {
    fontFamily: 'Heebo-Light',
    fontSize: 14,
    color: '#B3B3B3',
    marginTop: 10,
    paddingBottom: 20,
    borderBottomColor: '#707070',
    borderBottomWidth: 1,
    marginBottom: 20,
  },
  dimensiunePizzaText: {
    fontFamily: 'Heebo-Regular',
    fontSize: 13,
    color: '#999999',
    textAlign: 'center',
    marginTop: 10,
  },
  dimensiunePizza: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '48%',
    height: 131,
    borderWidth: 2,
    borderColor: '#999999',
    borderRadius: 10,
  },
  contactTitle: {
    fontFamily: 'Heebo-Bold',
    fontSize: 30,
    textTransform: 'uppercase',
    color: 'white',
    marginTop: 10,
    marginBottom: 10,
  },
  contactText: {
    fontFamily: 'Heebo-Light',
    fontSize: 16,
    color: 'white',
    marginBottom: 10,
  },
  input: {
    width: '100%',
    height: 45,
    marginBottom: 20,
    backgroundColor: 'black',
    fontFamily: 'Heebo-Light',
    fontSize: 14,
    color: 'white',
    paddingLeft: 20,
    borderRadius: 10,
  },
  placeholderStyle: {
    fontFamily: 'Heebo-Light',
    fontSize: 14,
    color: 'white',
  },
  termsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  termsText: {
    fontFamily: 'Heebo-Light',
    fontSize: 14,
    color: 'white',
    marginRight: 5,
    flexWrap: 'wrap'
  },
  termeniButton: {
    fontFamily: 'Heebo-Light',
    fontSize: 14,
    color: '#FFD101',
    flexWrap: 'wrap'
  },
  termsTextContainer: {
    marginLeft: 10,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  contactInformatiiText: {
    fontFamily: 'Heebo-Regular',
    fontSize: 18,
    color: 'white',
    textAlign: 'center',
    marginTop: 10,
  },
  contactInformatii: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  contactInformatiiElement: {
    width: '50%',
    marginBottom: 10,
  },
  sosElement: {
    // flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#999999',
    width: 85,
    height: 100,
  },
  sosElementModal: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 2,
    width: 110,
    height: 110,
  },
  swiperSosuriContainer: {
    width: '100%',
    height: 100,
    marginTop: 20,
  },
  adaugaSosText: {
    fontFamily: 'Heebo-Regular',
    fontSize: 10,
    textAlign: 'center',
    // marginTop: 3,
  },
  numberProducsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  piceContainer: {
    backgroundColor: 'black',
    flex: 1,
    height: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 10,
  },
  countText: {
    fontFamily: 'Heebo-Regular',
    fontSize: 20,
    color: '#808080',
  },
  countButton: {
    padding: 5,
  },
  ingredienteDecriere: {
    fontFamily: 'Heebo-Light',
    fontSize: 16,
    color: 'white',
    marginBottom: 20,
  },
  deliveryInfo: {
    flexDirection: "row",
    justifyContent: 'space-between',
    fontSize: 20,
    fontFamily: 'Heebo-Light',
    opacity: 0.5,
    color: '#fff',
  },
  containerDetaliiComanda: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "black",
    width: "100%",
    height: "100%",
    padding: 10,
    paddingBottom: 70,
  },
  cosTotal: {
    fontSize: 25,
    fontFamily: 'Heebo-Bold',
    color: '#FFD101',
  },
  cosTotalValoare: {
    fontSize: 34,
    fontFamily: 'Heebo-Bold',
    color: '#FFD101',
  },
  cosTotalLei: {
    fontSize: 21,
    fontFamily: 'Heebo-Regular',
  },
  containerAdresa: {
    backgroundColor: "black",
    padding: 20,
    flex: 1,
    width: "100%",
    marginBottom: 10,
  },
  containerAdresaDelivery: {
    // flex: 1, 
    flexDirection: "row",
    alignSelf: "flex-end",
    backgroundColor: "gray",
    alignItems: "center",
    width: "100%",
    height: "100%",
    paddingTop: 10,
    paddingBottom: 10,
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  btnEdit: {
    // height: 45,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
    backgroundColor: "#999999",
    textTransform: "uppercase",
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 15,
    fontFamily: 'Heebo-Medium',
    color: "white",
    overflow: 'hidden',
  },
  leftSwipeItem: {
    height: '100%',
    justifyContent: 'center',
    width: 100,
  },
  rightSwipeItem: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'flex-end',
    width: 100,
  },
  separator: {
    marginTop: 10,
    marginBottom: 20,
    borderBottomColor: '#707070',
    borderBottomWidth: 1,
  },
  containerCosGol: {
    backgroundColor: "#232323",
  },
  containerSlide1: {
    width: '80%',
    marginLeft: 'auto',
    marginRight: 'auto',
    height: 80,
    flexDirection: 'row',
    justifyContent: 'space-evenly'
  },
  containerSlide2: {
    width: '80%',
    marginLeft: 'auto',
    marginRight: 'auto',
    height: 80,
    flexDirection: 'row',
    justifyContent: 'space-evenly'
  },
  containerIngrediente: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: 20
  },
  containerInformatiiProdus: {
    flexDirection: "column",
    marginLeft: "5%",
    flex: 1,
  },
  containerProdus: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    width: '100%',
    flexWrap: 'wrap',
  },
  xModal: {
    alignSelf: "flex-end",
    marginTop: '5%',
    marginRight: '5%'
  },
  center: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center'
  },
  containerModal: {
    width: 340,
    height: 320,
    backgroundColor: '#161616',
  },
  btnModal: {
    width: 140,
    height: 55,
    backgroundColor: '#999999',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    textTransform: 'uppercase',
  },
  mesajModal: {
    fontSize: 16,
    fontFamily: 'Heebo-Regular',
    textAlign: 'center',
    color: 'white',
    width: '70%',
    alignSelf: 'center',
    marginBottom: '10%',
  },
  textInput: {
    width: '87%',
    backgroundColor: '#000000',
    borderRadius: 5,
    marginBottom: '3%',
    borderWidth: 0,
    height: 50,
    paddingLeft: 10,
  },
  pickerItem: {
    color: '#fff',
    fontFamily: 'Heebo-Light',
    fontSize: 16,
  },
  containerPicker: {
    height: 50,
    width: '90%',
    flexDirection: 'row',
    alignSelf: 'center',
    marginBottom: '3%'
  },
  totalModalIngrediente: {
    fontFamily: 'Heebo-Medium',
    fontSize: 20,
    color: '#ffd101',
    textTransform: 'uppercase',
  },
  comandaFinalizata: {
    fontSize: 25,
    fontFamily: 'Heebo-Bold',
    color: '#fff',
    textAlign: 'center',
  },
  textComandaFinalizata: {
    fontSize: 16,
    fontFamily: 'Heebo-Light',
    color: '#fff',
  },
  produsComanda: {
    fontSize: 20,
    fontFamily: 'Heebo-Bold',
    color: '#fff',
  },
  descriereProdusComanda: {
    fontSize: 14,
    fontFamily: 'Heebo-Regular',
    color: '#fff',
  },
  cantitateComanda: {
    fontSize: 18,
    fontFamily: 'Heebo-Regular',
    color: '#fff',
    marginTop: '5%',
    marginBottom: '10%',
  },
  produsPreviewComanda: {
    flex: 1,
    flexDirection: 'row',
    paddingLeft: '15%',
    paddingRight: '15%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalModalComanda: {
    fontSize: 20,
    fontFamily: 'Heebo-Medium',
    color: '#fff',
  },
  puncteModalComanda: {
    fontSize: 20,
    fontFamily: 'Heebo-Bold',
    color: '#fff',
    marginBottom: '10%'
  },
  loginTitle: {
    fontSize: 30,
    fontFamily: 'Heebo-Bold',
    color: '#ffd101',
    alignSelf: 'center',
    marginTop: '5%',
    marginBottom: 30,
    textTransform: 'uppercase',
  },
  loginButtonText: {
    color: 'white',
    textTransform: 'uppercase',
    fontFamily: 'Heebo-Medium',
    fontSize: 20,
    position: 'absolute',
    left: windowWidth / 2.3,
  },
  centerCreazaCont: {
    left: windowWidth / 2.9,
  },
  centerTrimiteParola: {
    left: windowWidth / 3.35,
  },
  dateCont: {
    fontSize: 16,
    fontFamily: 'Heebo-Light',
    color: '#fff',
    paddingTop: 10,
    paddingBottom: 30,
  },
  containerInput: {
    backgroundColor: '#000', borderRadius: 10, marginBottom: 10,
  },
  textPuncteleMele: {
    fontSize: 18,
    fontFamily: 'Heebo-Regular',
    color: '#fff',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 20,
  },
  reguli: {
    fontSize: 16,
    fontFamily: 'Heebo-Regular',
    color: '#fff',
    opacity: 0.5,
    textAlign: 'center',
  },
  idComanda: {
    fontSize: 16,
    fontFamily: 'Heebo-Regular',
    color: '#fff',
    opacity: 0.5,
    padding: 2,
  },
  oraLivrare: {
    fontSize: 22,
    fontFamily: 'Heebo-Bold',
    color: '#fff',
    textAlign: 'center',
  },
  textStareComanda: {
    fontSize: 22, fontFamily: 'Heebo-Regular', color: '#fff',
    marginLeft: 25,
  },
  procesLivrare: {
    fontSize: 19,
    fontFamily: 'Heebo-Regular',
    color: '#999',
    marginLeft: 25,
  },
  drawerLabel: {
    fontSize: 16,
    fontFamily: 'Heebo-Light',
    color: '#fff',
  },
  salutUser: {
    fontSize: 18,
    fontFamily: 'Heebo-Regular',
    color: '#fff',
  },
  password: {
    position: 'absolute', right: '3%', top: '35%'
  }
});